[sniffer]
# Enable packet capture
enabled = yes
# tcpdump path
tcpdump = /usr/sbin/tcpdump
# Sniffer interface
bpf = not (dst host {{GATEWAY_IP}} and dst port 2042)

[services]
enabled = yes

[reboot]
enabled = yes
