[cuckoo]
machinery = {{MACHINERY}}
memory_dump = off
terminate_processes = off
reschedule = off
max_analysis_count = 0
max_machines_count = 10
freespace = 50000
tmppath = /tmp
rooter = /tmp/cuckoo-rooter

[resultserver]
ip = {{RESULT_SERVER_IP}}
port = 2042
force_port = yes

[processing]
analysis_size_limit = 134217728

[database]
connection = {{DB_CONNECTION}}
timeout = 60
