[routing]
# Default network routing mode: none, internet, drop, tor, inetsim
route = {{ROUTING_MODE}}

# Analysis network interface
internet = {{CAPE_INTERFACE}}

# Auto route on submission
auto_rt = no

[inetsim]
enabled = no
server = 127.0.0.1

[tor]
enabled = no
dns_port = 5353
proxy_port = 9050

[vpn]
enabled = no
